theme: minima
title: Learning to Deblur and RotateMotion-Blurred Faces
author: Givi Meishvili, Attila Szabo, Simon Jenni, Paolo Favaro
email: givi.meishvili@inf.unibe.ch
description: This is the project page for our BMVC2021 paper titled "Learning to Deblur and RotateMotion-Blurred Faces"